---
- hosts: windows
  tasks:
    - name: Ensure Chocolatey installed from chocolatey repo
      chocolatey.chocolatey.win_chocolatey:
        name: chocolatey
        state: present
        source: https://chocolatey.org/install.ps1
    - name: Install softwares
      chocolatey.chocolatey.win_chocolatey:
        name:
          - git
          - vim
          - python3
          - unzip